### PR TITLE
Version 2 Upgrade

### PR DESCRIPTION
**Pull request by gabrielmontagne**
## Description

This PR brings in a rewrite of _fun_ with
- ES6 syntax
- Update to new module definitions
- Cleaner, more portable build
- Cleaner repository structure
- Cleaner documentation and project contribution files.
- Improved test coverage.
## Motivation and Context

This PR should be considered a major version update for _fun_.
The API is reduced from V1 -- but because of legacy build structure and component definition, V1 was not really usable.  
We can port the remaining legacy code as it is needed.
## How Was This Tested?

Automated unit tests from V1 have been brought forward and strengthened.
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My change follows the style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the [contribution guidelines](../CONTRIBUTING.md)
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Poetro** [comment]
Ok, I understand the removal of some array, string and object related functions, although we also kept some. Why did you remove some fundamental functions like `partial` and `trampoline`?

**Comment by gabrielmontagne** [comment]
Hey @Poetro , these just haven't been ported over.  Thought we could bring them across as we need them -- driven by `zambezi/grid` or `zambezi/d3-utils` .  But, thinking about it, we had complete coverage (thanks to you! ;-) so moving a bit more of these across should be straightforward. 

No need to rush this.  I'll review what is not yet here.  If you have favs you'd like to "make it" to this version, let me know and I'll move them to the top.

**Comment by gabrielmontagne** [comment]
... that being said, I do feel reluctant to re-introduce the stuff that has been already implemented in other libraries like [d3-array](https://github.com/d3/d3-array) or [underscore](https://github.com/jashkenas/underscore).

**Comment by gabrielmontagne** [comment]
What if we go like this,

## First things to move across for merging this, in rough order of usefulness,
1. [x] fun/and.js
2. [x] fun/or.js
3. [x] fun/some-result.js
4. [x] fun/modulo.js
5. [x] fun/trampoline.js
6. [x] fun/array/trampoline-filter.js
7. [x] fun/array/trampoline-flatten.js
8. [x] fun/array/trampoline-merge-sort.js

## And then, for a V2.1, less useful/interesting stuff.
1. [ ] fun/array/trampoline-flatten.js
2. [ ] fun/array/flatten-by.js
3. [ ] fun/array/flatten.js
4. [ ] fun/array/index-on.js
5. [ ] fun/compare-against.js
6. [ ] fun/compare-on.js
7. [ ] fun/compare-with.js
8. [ ] fun/object/unwrap.js
9. [ ] fun/object/wrap.js

## And some stuff for later times
1. string/escape-regex.js
2. multiply.js
3. string/append.js
4. string/lower.js
5. string/prepend.js
6. string/slugify.js
7. string/upper.js
8. sum.js
9. tap.js
10. instantiate.js
11. array/difference.js
12. array/symmetric-difference.js
13. array/reverse.js
14. array/union.js
15. join.js

**Comment by gabrielmontagne** [comment]
@Poetro , man, I move some more stuff across. I think it's good for this version.
What do you think?

**Comment by Poetro** [comment]
I see you checked `or` in the list, but I do not see the file.

**Comment by gabrielmontagne** [comment]
Yeah, @Poetro , had forgotten about that one.  It's now in.

**Comment by Poetro** [comment]
:+1:

**Pull request merged**
